name: Test Environment
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print Environment
        run: |
          echo "Environment: dev"

  staging:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Print Environment
        run: |
          echo "Environment: stg"

  production:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: https://github.com/peacepiece7/git-action-playground
    steps:
      - name: Print Environment
        run: |
          echo "Environment: prd"
